[data]
num_nodes = 325
lag = 12
horizon = 12
val_ratio = 0.2
test_ratio = 0.2

normalizer = std
column_wise = False

[model]
embed_dim = 2
rnn_units = 64
num_layers = 2
mp_num_workers = 8
accelerate = True

input_dim = 1
output_dim = 1
cheb_order = 1

stru_dec_drop = 0.1
stru_dec_proj = false
pipeline = pretrain

[train]
batch_size = 64
epochs = 200
lr_init = 0.003
num_runs = 1

loss_func = mae
seed = 12
lr_decay = False
lr_decay_rate = 0.3
lr_decay_step = 5,20,40,70
early_stop = False
early_stop_patience = 15
grad_norm = False
max_grad_norm = 5
real_value = True

opt_name =  adam
pt_lr =  0.003
pt_wd =  0
train_epoch =  200
pt_sched_policy =  None
pt_num_epoch_fix_lr =  0
pt_decay_step =  0
pt_gamma =  0
pt_milestones =  []
pt_clip_grad =  None

  # finetune specific if learning in pretrain+finetune
ft =  true
lr_enc =  0.003
lr_dec =  0.003
wd_enc =  0
wd_dec =  0
ft_epoch =  200
ft_sched_policy =  None
ft_num_epoch_fix_lr =  0
ft_decay_step =  0
ft_gamma =  0
ft_milestones =  []
ft_clip_grad =  None
de_mlp =  true

eps_enc = 1e-8
eps_dec = 1e-8

pt_eps = 1e-8
  # extras
patience =  -1

[test]
mae_thresh = None
mape_thresh = 0.

[log]
log_step = 20
plot = False

[mask_specs]
epoch_wise_mask = false
mask_s = 0.2
mask_f = 0.3
mask_s_strategy = rw_fill
mask_f_strategy = patch_uniform
normalize = false
patch_length = 2
with_negative = false
walks_per_node = 10
walk_length = 20
start = node
p = 1
q = 1

[loss_specs]
sl_weight= 2
fl_weight= 1.0
sl_type= 'cls_boost'
fl_type= 'reg_l1'